[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
market = "H8qo8b9avc5GdWG4jTPPmoN9edrLKpQtQDSJ3C9yZHuQ"
treasury = "FM1cd5jwHPnnr1kNVnW92EXYsPhcbKrQTfjSiPxknZYr"
voting_tokens = "7xv7mZrxDGDq49irVDsCZjjLxQCqCzhQhRuApQnXEhqL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000000 tests/**/*.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = ".anchor/metaplex.so"
