[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
market = "EogDadUrpwu6eZuygUVnTShWTAKscYdNgAqVbspvys5T"
voting_tokens = "4EqPeR7tt5mPq4PgjS5Wa4gqNjjFDa4ATLTFL1waXaNk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000000 tests/**/*.ts"
test-market = "yarn run ts-mocha -p ./tsconfig.json -t 1000000000 tests/market/*.ts"
test-voting-tokens = "yarn run ts-mocha -p ./tsconfig.json -t 1000000000 tests/voting_tokens/*.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = ".anchor/metaplex.so"
